# Generated by Django 4.2 on 2024-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'در انتظار'), ('in_progress', 'در حال انجام'), ('done', 'تکمیل شده'), ('blocked', 'مسدود شده'), ('cancelled', 'لغو شده'), ('closed', 'بسته شده'), ('reopened', 'بازگشایی شده'), ('approved', 'تایید شده'), ('review', 'در حال بررسی'), ('test', 'در حال آزمایش'), ('delivered', 'تحویل داده شده'), ('deployed', 'مستقر شده'), ('deferred', 'تأخیر افتاده'), ('duplicate', 'تکراری'), ('invalid', 'نامعتبر'), ('not_a_bug', 'خطای نیست')], max_length=50, verbose_name='وضعیت'),
        ),
    ]
