# Generated by Django 4.2 on 2024-07-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_assigned_to_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان\u200cها'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='admin',
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.organization', verbose_name='سازمان'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.organization', verbose_name='سازمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مدیر سازمان',
                'verbose_name_plural': 'مدیران سازمان',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='managed_organizations', through='tasks.OrganizationAdmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
