# Generated by Django 4.2 on 2024-07-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_organization_options_remove_organization_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_task_custom', 'Can view task'), ('change_task_custom', 'Can change task'), ('delete_task_custom', 'Can delete task')), 'verbose_name': 'تسک', 'verbose_name_plural': 'تسک\u200cها'},
        ),
    ]
